#pragma once

enum TEXTYPE { TEX_SINGLE, TEX_MULTI };
enum SCENEID { SCENE_LOGO, SCENE_TITLE, SCENE_TOWN, SCENE_STAGE, SCENE_END };
enum OBJID { OBJ_BACKGROUND, OBJ_LAYER, OBJ_TILEMAP, OBJ_MAPOBJ, OBJ_WEAPON, OBJ_ACTOR, OBJ_BULLET, OBJ_EFFECT, OBJ_UI, OBJ_END };
enum DATAID { PLAYER_DATA, PLAYER_MATRIX };
enum COLLTILEID { COLL_DEFAULT, COLL_UPDIG, COLL_DOWNDIG, COLL_RECT, COLL_LINE, COLL_DUNGEON, COLL_ROOM};