#pragma once

enum TEXTYPE { TEX_SINGLE, TEX_MULTI };
enum SCENEID { SCENE_LOGO, SCENE_STAGE, SCENE_END };
enum OBJID { OBJ_BACK, OBJ_PLAYER, OBJ_EFFECT, OBJ_UI, OBJ_END };
enum DATAID { PLAYER_DATA, PLAYER_MATRIX };
enum COLLTILEID { COLL_DEFAULT, COLL_UPDIG, COLL_DOWNDIG, COLL_RECT, COLL_LINE, COLL_DUNGEON, COLL_ROOM};